### ISSUE TITLE
Create site for Relaton

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/relaton.com#1]
Relaton is the interoperable data model for citations, based on the international standard for citations, ISO 690.

* Relaton models: https://github.com/riboseinc/relaton-models
* Relaton CLI gem: https://github.com/riboseinc/relaton-cli
* Relaton core gem: https://github.com/riboseinc/relaton 

Relaton supports multiple bibliographic sources (all of them from standards bodies, for now)
* Relaton for ISO: https://github.com/riboseinc/relaton-iso
* Relaton for IETF: https://github.com/riboseinc/relaton-ietf
* Relaton for CalConnect: https://github.com/riboseinc/relaton-calconnect
* Relaton for GB: https://github.com/riboseinc/relaton-gb

**Comment by ronaldtse** [comment]
The Relaton system is used to power the official CalConnect document registry.

**Comment by ronaldtse** [comment]
@strogonoff we can copy the Metanorma site structure over since the structure is also similar. However we need to think about how we can synchronize the structure as we improve them...

**Comment by ronaldtse** [comment]
* IETFBib https://github.com/riboseinc/ietfbib
* ISOBib https://github.com/riboseinc/isobib
* IECBib https://github.com/riboseinc/iecbib
* GBBib https://github.com/riboseinc/gbbib

**Comment by strogonoff** [comment]
I don’t think we should go out of our way to perfectly synchronize structure just for the sake of it, these are different projects with their own separate homes. As we improve [the Open Project framework](https://github.com/riboseinc/jekyll-theme-open-project), sites using it get the same new features as they bump to newer version (and as for features that don’t make it into OPF because they’re are too specific, some divergence is not a crime).

**Comment by ronaldtse** [comment]
Good point, diversity is not a crime. Yet the structured nature of Relaton (bibliography for standards) and Metanorma (documents for standards) are so similar that the same site structure will help.

**Comment by strogonoff** [comment]
The structure is ultimately similar across the board: some software, some specs, and project-wide getting-started docs & tutorials… I think I get your point though!

**Comment by strogonoff** [comment]
Why would I want to use Relaton if I’m authoring let’s say a CalConnect document?

**Comment by ronaldtse** [comment]
Relaton is used in Metanorma to auto-fetch bibliographic references. Bibliographic references contain the document ID, title, authors, edition year, copyright information, etc.

Usually when you write a document, you have to Google search for the number/title and manually copy/paste them in your document.

With Relaton, it's all automatic.

Relaton also allows you to interchange bibliographic data, for example, you can have a set of references stored in a Relaton local cache. Such as via the `relaton fetch` command.

In addition, we are developing a "Relaton registry" function that serves up Relaton bibItem collections and Relaton bibItems. That is useful for the automatic retrieval of bibliographic information.

**Comment by strogonoff** [comment]
I’m not sure what causes the build error, configuration and Rakefile used is identical to Metanorma but the output says:

```
JEKYLL_ENV=production jekyll build --config=_config.yml
Configuration file: /home/travis/build/riboseinc/relaton.com/_config.yml
Configuration file: _config.yml
 Theme Config file: /home/travis/.rvm/gems/ruby-2.5.1/gems/jekyll-theme-open-project-1.1.25/_config.yml
            Source: /home/travis/build/riboseinc/relaton.com
       Destination: /home/travis/build/riboseinc/relaton.com/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
Invalid theme folder: _data
                    done in 2.683 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
rake aborted!
ArgumentError: ./output does not exist
/home/travis/.rvm/gems/ruby-2.5.1/gems/html-proofer-3.9.3/lib/html-proofer.rb:30:in `check_directory'
/home/travis/build/riboseinc/relaton.com/Rakefile:86:in `block (2 levels) in <top (required)>'
/home/travis/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/home/travis/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `eval'
/home/travis/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => test:production
(See full trace by running task with --trace)
The command "bundle exec rake test:production && rake build:production" exited with 1.
```

**Comment by strogonoff** [comment]
@ronaldtse could you help take a look as to what may be causing the missing `output` directory during CI build?

**Comment by ronaldtse** [comment]
It's still failing due to lack of `/output`. I think the `$outputDir` variable in Rakefile is wrong, it probably should point to `_site` because the output resides there. Not sure why it's not failing at `metanorma.com`...

When I manually create `output/`, the code runs correctly.

**Comment by strogonoff** [comment]
> Not sure why it's not failing at metanorma.com

That is indeed what I find strange, I thought perhaps it could be configured somewhere in the login-protuected Travis dashboard

**Comment by strogonoff** [comment]
> I've set the site variables at Travis properly, but if this issue persists it is due to the code...

I can verify that jekyll build works locally, so it must be the logic in Rakefile, .travis-ci.yml, or settings in Travis or GitHub

**Comment by ronaldtse** [comment]
The Travis command of “rake test:production” shows the same error on my machine. So it’s a real error that can be reproduced.

**Comment by strogonoff** [comment]
I never doubted the error is real! :D

Looks like there’s been a breaking change in the API of html-proofer.

**Comment by strogonoff** [comment]
https://github.com/riboseinc/jekyll-theme-open-project/commit/7991698d9e559ac575d8cd956535a35f42f034a1

**Comment by ronaldtse** [comment]
I've deployed the site by disabling the HTML proof test. The problem is that the proof test was never actually run properly, so it never did anything. We need to configure it to actually work and resolve links 😉

**Comment by strogonoff** [comment]
@ronaldtse wait so the fix I pushed was not enough? Setting the version for html-proofer fixed the issue for me.

**Comment by strogonoff** [comment]
Let me know, if html proofing causes breakage I’ll update the setup docs

**Comment by ronaldtse** [comment]
The issue is that the htmlproofer has never worked. When the tests are run, the proofer actually tests the pages and the links it tests cannot be resolved (esp since it’s looking to resolve links to “relaton.com). If you can make the proofer work, that’ll be great and we can re-enable the tests. 

There are other failures like pages missing, favicon missing (because they are really missing!).

**Comment by strogonoff** [comment]
@ronaldtse OK I see that fixing html-proofer version fixed the build, but you disabled proofing in an unrelated feature to speed up generation.

I think failures are good, why disable them? We get to them eventually! Where can I see them, Travis log?

**Comment by strogonoff** [comment]
I believe what blocked the first deploy was the way new html-proofer version started treating output directory flag after a backwards-incompatible change (fixing that gem’s version eliminated that error for me). That said, I have no objection on other points.
