### ISSUE TITLE
Not accessible without the www. prefix

### ISSUE THREAD

**Issue by strogonoff** [riboseinc/relaton.com#4]
Not sure if intended behavior, but different from e.g. metanorma.com

**Comment by ronaldtse** [comment]
Bug, not feature. Will fix.

**Comment by ronaldtse** [comment]
Hmm... Even metanorma.com isn't working now.

**Comment by ronaldtse** [comment]
Very strange. Originally I got this:

![screen shot 2019-01-03 at 11 47 42 am](https://user-images.githubusercontent.com/11865/50623092-6dc47200-0f4d-11e9-87da-e143aeea0b9c.png)

And then now it's working. There has been no configuration change. I'm pretty sure it was an AWS problem.

CloudFront may be stuck with its cache when S3 wasn't available (not sure why/how/when), and it's working now.

**Comment by strogonoff** [comment]
Strange, agreed, likely AWS fluke. I sometimes hit metanorma.com without the prefix so I’d notice if it was consistently down.
